apiVersion: v1
kind: Service
metadata:
  name: simple-rest
  labels:
    app: simple-rest
spec:
  ports:
  - port: 5000
  selector:
    app: simple-rest
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    app: simple-rest
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-rest-deployment
  labels:
    app: simple-rest
spec:
  selector:
    matchLabels:
      app: simple-rest
  template:
    metadata:
      labels:
        app: simple-rest
    spec:
      containers:
      - image: akring1729/simple-rest:0.1
        name: simple-rest
        ports:
          - containerPort: 5000
            name: flask
        volumeMounts:
          - name: simple-rest-persistent-storage
            mountPath: /data
      volumes:
      - name: simple-rest-persistent-storage
        persistentVolumeClaim:
          claimName: pvc

